-- Postgres mirror of the pipeline's SQLite schema.
-- Column types stay as close as possible so queries behave identically:
-- dates and timestamps remain TEXT, exactly as the Python tooling writes them.

CREATE TABLE IF NOT EXISTS sponsors (
  sponsor_id         INTEGER PRIMARY KEY,
  org_name           TEXT NOT NULL,
  org_name_raw       TEXT NOT NULL,
  legal_name         TEXT NOT NULL,
  trading_name       TEXT,
  name_key           TEXT NOT NULL,
  town               TEXT,
  county             TEXT,
  country            TEXT,
  is_london          INTEGER DEFAULT 0,
  company_type       TEXT,
  industry           TEXT,
  industry_conf      TEXT,
  industry_score     INTEGER,
  industry_alt       TEXT,
  industry_evidence  TEXT,
  is_franchise       INTEGER DEFAULT 0,
  n_routes           INTEGER DEFAULT 0,
  best_rating        TEXT,
  has_skilled_worker INTEGER DEFAULT 0,
  is_canonical       INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS routes (
  route_id        INTEGER PRIMARY KEY,
  sponsor_id      INTEGER NOT NULL,
  route           TEXT NOT NULL,
  tier            TEXT,
  rating          TEXT,
  type_rating_raw TEXT
);

CREATE TABLE IF NOT EXISTS fit (
  sponsor_id INTEGER NOT NULL,
  persona    TEXT NOT NULL,
  score      DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (sponsor_id, persona)
);

CREATE TABLE IF NOT EXISTS enrichment (
  sponsor_id        INTEGER PRIMARY KEY,
  ch_company_number TEXT,
  ch_official_name  TEXT,
  ch_status         TEXT,
  ch_incorporated   TEXT,
  ch_sic_codes      TEXT,
  ch_sic_desc       TEXT,
  ch_address        TEXT,
  ch_postcode       TEXT,
  ch_town           TEXT,
  ch_category       TEXT,
  ch_accounts_cat   TEXT,
  ch_size_band      TEXT,
  ch_age_years      DOUBLE PRECISION,
  ch_match_method   TEXT,
  ch_match_score    DOUBLE PRECISION,
  website           TEXT,
  careers_url       TEXT,
  linkedin_url      TEXT,
  employee_estimate TEXT,
  verified_industry TEXT,
  notes             TEXT,
  checked_at        TEXT,
  ats_type          TEXT,
  ats_slug          TEXT,
  web_confidence    DOUBLE PRECISION,
  web_checked_at    TEXT,
  geo_verified      INTEGER,
  group_key         TEXT
);

CREATE TABLE IF NOT EXISTS pipeline (
  sponsor_id      INTEGER PRIMARY KEY,
  batch_date      TEXT,
  batch_seq       INTEGER,
  persona         TEXT,
  priority        DOUBLE PRECISION,
  status          TEXT DEFAULT 'queued',
  role_target     TEXT,
  contact_name    TEXT,
  contact_email   TEXT,
  application_url TEXT,
  resume_path     TEXT,
  cover_path      TEXT,
  applied_at      TEXT,
  outcome         TEXT,
  notes           TEXT
);

CREATE TABLE IF NOT EXISTS vacancies (
  vacancy_id  INTEGER PRIMARY KEY,
  sponsor_id  INTEGER NOT NULL,
  title       TEXT NOT NULL,
  url         TEXT,
  location    TEXT,
  source      TEXT,
  persona     TEXT,
  match_score DOUBLE PRECISION,
  posted      TEXT,
  found_at    TEXT,
  in_uk       INTEGER
);

CREATE TABLE IF NOT EXISTS events (
  event_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sponsor_id INTEGER,
  ts         TEXT NOT NULL,
  kind       TEXT NOT NULL,
  detail     TEXT
);

CREATE INDEX IF NOT EXISTS ix_sponsors_name  ON sponsors (org_name);
CREATE INDEX IF NOT EXISTS ix_routes_sponsor ON routes (sponsor_id);
CREATE INDEX IF NOT EXISTS ix_fit_persona    ON fit (persona, score DESC);
CREATE INDEX IF NOT EXISTS ix_pipeline_batch ON pipeline (batch_date, batch_seq);
CREATE INDEX IF NOT EXISTS ix_vac_sponsor    ON vacancies (sponsor_id);
CREATE INDEX IF NOT EXISTS ix_vac_persona    ON vacancies (persona, match_score DESC);
CREATE INDEX IF NOT EXISTS ix_ev_sponsor     ON events (sponsor_id);
